### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by Kent4Ever** [rayvbr/URISigningSpec#9]
The new method using JWT definitely cleaned up the draft by removing the signing and validating signature sections. But this is no longer backwards compatible for the simple case of using query strings for client IP and expiry time. Sorry, if this topic was already discussed. Given the tradeoffs, I'm OK with using JWT and losing backward compatibility as well as not compatible with existing proprietary URL signing methods used by companies.

**Comment by PSUdaemon** [comment]
When you say `...the simple case of using query strings for client IP and expiry time.` you mean multiple query parameters? Even in the previous revision the draft was using one query param with a base64 encoded value of a string (that admittedly looked a lot like a query string) with those values in it. It was strongly recommended (read dictated) to the WG that we should not be using multiple query params.

**Comment by Kent4Ever** [comment]
OK. The old method of IE's became JWT claims. My mind jumped back a few years and forgot about "getting off the lawn".
